// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropiedadesMinimalApi.Datos;

#nullable disable

namespace PropiedadesMinimalApi.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropiedadesMinimalApi.Modelos.Propiedad", b =>
                {
                    b.Property<int>("IdPropiedad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropiedad"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPropiedad");

                    b.ToTable("Propiedad");

                    b.HasData(
                        new
                        {
                            IdPropiedad = 1,
                            Activa = true,
                            Descripcion = "Es la de estados unidos",
                            FechaCreacion = new DateTime(2023, 11, 28, 14, 12, 6, 175, DateTimeKind.Local).AddTicks(730),
                            Nombre = "Casa Blanca",
                            Ubicacion = "Washintong D.C"
                        },
                        new
                        {
                            IdPropiedad = 2,
                            Activa = false,
                            Descripcion = "Es la de estados Verdes",
                            FechaCreacion = new DateTime(2023, 11, 28, 14, 12, 6, 175, DateTimeKind.Local).AddTicks(755),
                            Nombre = "Casa Azul",
                            Ubicacion = "Arizona D.C"
                        },
                        new
                        {
                            IdPropiedad = 3,
                            Activa = true,
                            Descripcion = "Es la de estados Rojos",
                            FechaCreacion = new DateTime(2023, 11, 28, 14, 12, 6, 175, DateTimeKind.Local).AddTicks(760),
                            Nombre = "Casa Negra",
                            Ubicacion = "California D.C"
                        },
                        new
                        {
                            IdPropiedad = 4,
                            Activa = false,
                            Descripcion = "Es la de estados Amarillos",
                            FechaCreacion = new DateTime(2023, 11, 28, 14, 12, 6, 175, DateTimeKind.Local).AddTicks(765),
                            Nombre = "Casa Rosa",
                            Ubicacion = "Washintong C.D"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
